development:
  adapter: postgresql
  database: temporis-v-dev
  username: postgres
  password : password
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: temporis-v-test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: temporis-v-production
  pool: 5
  timeout: 5000